### ISSUE TITLE
[FEATURE REQUEST]Support for OUT command

### ISSUE THREAD

**Issue by nileshpatra** [debjitbis08/sim8085#14]
I think we should add in a 'OUT' command to display the data of the accumulator onto a seven segment display. We will also need to simulate a SSD in the process If you think this feature is okay, should I start working on it? :)

**Comment by debjitbis08** [comment]
Sorry for the late reply.

I think this will be good feature. Do you a have design we can look at?

**Comment by sonikamakam** [comment]
YES

**Comment by debjitbis08** [comment]
Implemented in V2.
