### ISSUE TITLE
cnz not working

### ISSUE THREAD

**Issue by Timothy-C** [debjitbis08/sim8085#15]
EDIT: I realize that my code may not be valid, I apologize in advance if this is so

```
jmp start

start: nop
mvi b,88h
mov a,b
cnz functionname
hlt

functionname: mov c,a
ret
```

When going through line-by-line, instead of calling functionname subroutine, the instruction will jump to line 1. However, when you change "cnz" to "call", it will work properly.

**Comment by debjitbis08** [comment]
Seems to be working fine now.
