### ISSUE TITLE
call, ret not working

### ISSUE THREAD

**Issue by himeshbhatia** [debjitbis08/sim8085#3]
Hello, thanks for fixing the jz problem. Sorry to bother you again, but the call/ret sequence doesn't seem to work either; could you look into this?
Your compiler has quite a good ui and is easy to use, so I dont want to use any other simulator if possible. Thanks again.

Program:

mvi a, 0ah
mvi b, 1ch
call adsbr
sta 0100h
hlt

adsbr: add b
ret

**Comment by debjitbis08** [comment]
Thanks for reporting these issues. This really helps improve the experience for everyone using this tool. Do not hesitate to file more issues. I may not be able to fix them immediately but it's good to know what is buggy.

This should be fixed now. I have not tested all flavours of CALL instructions, so, please let me know if you find more issues.
