### ISSUE TITLE
Unexpected behavior by the JNC statement

### ISSUE THREAD

**Issue by chajjern2** [debjitbis08/sim8085#32]
`MVI C, 00H`
`LXI H, 28E0H`
`MOV B, M`
`INX H`
`MOV A, M`
`ADD B`
`JNC 080DH`
`INR C`
`INX H`
`MOV M, A`
`INX H`
`MOV M, C`
`HLT `

It's a simple adder which stores carry too. So, when I run it, there are two ways this program goes depending on the values to be added (at memory location 28E0H and 28E1H).
If the sum generates a carry, it works perfectly, but if it doesn't generate a carry, program doesn't run and says infinite loop detected. I tried to debug it by using the "Run one instruction" and it turns out JNC carry statement doesn't work like it should. That is, instead of setting PC register to 080DH, it sets it to 100DH.

**Comment by debjitbis08** [comment]
Fixed.
