### ISSUE TITLE
No way to change where the program is stored

### ISSUE THREAD

**Issue by CodeFingers809** [debjitbis08/sim8085#40]
I am sorry but this is a very small ask.
Can u pls add a way to change where the program is stored. Currently it is stored on 0x0800 but I wanted to change it and found to way to be able to.

**Comment by arnabpal16** [comment]
I WOULD LIKE TO SOLVE THIS ISSUE PLEASE ASSIGNED ME

**Comment by debjitbis08** [comment]
Solved in v2 by implementing the ORG directive.
