### ISSUE TITLE
`AC` flag not set with `SBB`

### ISSUE THREAD

**Issue by devanshshukla99** [debjitbis08/sim8085#44]
On executing the following code, I think both `AC` and `CY` flags should set;
however, only the `CY` flag sets in the simulator.

```assembly
mvi a, 1fh
mvi b, ffh
sbb b
```

**Comment by debjitbis08** [comment]
GNUSim8085 produces the same output. Need to check manually and other emulators.

**Comment by debjitbis08** [comment]
This is indeed an bug because of how 8085 does subtraction. Subtraction happens using two's complement addition. Quoting from the 8085 programming manual

> SBB incorporates the carry flag by adding it to the byte to be subtracted from the accumulator. It then subtracts the result from the accumulator by using two's complement addition.

Fixed it by doing the exact same process in emulation.
