### ISSUE TITLE
Decimal notation not supported?

### ISSUE THREAD

**Issue by cyberjupiter** [debjitbis08/sim8085#5]
I tried putting 'D' at the end of an operand and it gives me 
>  Expected comment, end of input, line end, or whitespace but "D" found.

Nothing big really, removing the 'D' or leaving any notation indicates to the assembler that it is a decimal value right?

**Comment by debjitbis08** [comment]
Yes, by default the numeric values are assumed to be decimal. Although, numeric literals ending with a "D" should also work. Seems like a bug if there is parse error.

I will look into it.

**Comment by debjitbis08** [comment]
Should be fixed in now.
