### ISSUE TITLE
CMP instruction does not trigger Carry flag

### ISSUE THREAD

**Issue by cyberjupiter** [debjitbis08/sim8085#6]
A simple program to arrange numbers in descending order:
```
	   MVI C,04

RELOOP:	   MVI B,04
	   LXI H,2201H

LOOP: 	   MOV A,M
	   INX H
	   CMP M
	   JNC NOSWAP
	   JZ NOSWAP
	   MOV D,M
	   MOV M,A
	   DCX H
	   MOV M,D
	   INX H

NOSWAP:	   DCR B
	   JNZ LOOP
	   DCR C
	   JNZ RELOOP
	   HLT
```
Assuming you have put some numbers consecutively in memory, in my case it was
`01 05 03 02 04`
starting at 2201H.
The CMP does not raise the carry flag.

**Comment by debjitbis08** [comment]
Thanks for reporting this. Should be fixed now.
