### ISSUE TITLE
SHLD issue when storing at locations 0x000B, 0x00B0 and 0x0B00  memory locations

### ISSUE THREAD

**Issue by Gaurav-Shah05** [debjitbis08/sim8085#60]
`
;<Program title>

jmp start

;data

;code
start: nop

LXI H,1001H;

SHLD 000BH;

hlt

`

On compiling the following code, it throws the error,  _"Expected comment, end of input, line end, or whitespace but "0" found."_  
There's no issue when the memory location value 0x000B is changed with any other location like 0x000C or 0x000D. 

![image](https://github.com/debjitbis08/sim8085/assets/73552538/9e2ecf9c-cd60-4d20-a655-cd857feb3a9f)

_compilation issue when storing at 0x000B_

![image](https://github.com/debjitbis08/sim8085/assets/73552538/f38b2d50-9877-4b7c-b583-a95c6361deee)

_The code runs perfectly when the location changes to 0x000C_

There's no issue in compiling when the **SHLD 000BH** is changed to **SHLD 000B**, but then, on executing the code, the location 0x0B00 is not updated with the value of the LH register pair.

![image](https://github.com/debjitbis08/sim8085/assets/73552538/787eb2bc-dc8f-4712-9d6b-02b56a3b994a)

**Comment by debjitbis08** [comment]
This is because the parser confuses `000BH` etc. to be binary literal instead of hex. For now, `0x000B` syntax can be used. Will be fixed in V2.
