### ISSUE TITLE
[BUG] Program couldn't be assembled and compiled

### ISSUE THREAD

**Issue by Subhranil2004** [debjitbis08/sim8085#61]
Consider the program for adding consecutive numbers.
If the result doesn't produce carry -> Display result through the `OUT` port.
Else display `01` thru `OUT` port.
```asm
        LXI H, 00F0H        ; Initialize HL pair to point to memory location 00F0H
        MVI C, 05H          ; Initialize byte counter to 5
        SUB A               ; Clear the accumulator (A = 0)

NEXT:   ADD M               ; Add the byte at memory location pointed to by HL to A
        JC STOP             ; If carry is generated, jump to STOP
        INX H               ; Increment HL to point to the next memory location
        DCR C               ; Decrement byte counter
        JNZ NEXT            ; If byte counter is not zero, repeat the loop
        OUT 00H             ; Output the sum to the output port (assuming port address is D8H)
        HLT                 ; Halt the program

STOP:   MVI A, 01H          ; Load 01H into A to indicate carry was generated
        OUT 00H             ; Output 01H to the output port (assuming port address is D8H)
        HLT                 ; Halt the program
```

This couldn't be assembled and compiled.
Error shown: 
```
 Label STOP is not defined. Also check the label definition, there may be some issues on that line.
```

Image for reference:
![image](https://github.com/user-attachments/assets/ba93fb26-ed04-47eb-ac15-89a22d840424)

PS: The program successfully executed on GNUSim8085

**Comment by debjitbis08** [comment]
This is because the `OUT` instruction is not supported yet. It will take some time for me to add support for I/O.

Will try to display better error message until then.

**Comment by debjitbis08** [comment]
The `OUT` instruction is now supported on V2.

**Comment by Subhranil2004** [comment]
> The `OUT` instruction is now supported on V2.

Yes, it's working fine. The UI looks cool as well 🎉
