### ISSUE TITLE
Wanted to run a code in infinite loop. But not supported

### ISSUE THREAD

**Issue by Aparup123** [debjitbis08/sim8085#67]
I wanted to run a code to generate a square wave but it is not possible as the software doesn't support infinite loop.

### My code 
``` asm
ORG 00H

WHILE:
  MVI A,00H
  OUT 02H
  CALL DELAY
  MVI A,01H
  OUT 02H
  JNZ WHILE



DELAY:
  MVI B, 0FFH
  LABEL:
    DCR B
    JNZ LABEL
  RET
  
```
### Error
`infinite loop detected`

**Comment by debjitbis08** [comment]
This is not supported right now and is not something planned. This would require support for not only infinitely running code, but also timing simulation for each instruction. Maybe sometime in future.

**Comment by Aparup123** [comment]
ok

**Comment by debjitbis08** [comment]
This is now implemented.
