### ISSUE TITLE
Infinite loop detected error. PS: THERE'S NO INFINITE LOOP AND I HAVE ADDED 'HLT' STATEMENT AS WELL

### ISSUE THREAD

**Issue by AshishRana1808** [debjitbis08/sim8085#69]
**### This is the assembled code generated but I am getting a "Infinite loop detected" Error here, and a recommendation that probably I have forgotten to add a hlt statement. Can anyone suggest what's wrong here**

![Screenshot 2024-11-13 110145](https://github.com/user-attachments/assets/66f53710-5cc7-4dc2-b760-8be30c63fdcb)

**Comment by debjitbis08** [comment]
Since you added a ORG directive, have you added the start address in the input box which is available near the run button?

**Comment by AshishRana1808** [comment]
well, I didn't knew about that, I checked it and yes even after entering the start address, I am facing same issue.

**Comment by debjitbis08** [comment]
Added a fix. It should work now.
