### ISSUE TITLE
STAX D command not working

### ISSUE THREAD

**Issue by pranabendra** [debjitbis08/sim8085#7]
I wrote this following program to convert a hex digit to its ASCII value(in hex) stored at 0080H.  

```asm
	lxi h,0080h
        lxi d,0090h
        mov a,m
        mvi b,00h
r1:     cpi 10h
        jnc c1
        cpi 0Ah
        jc c2
        adi 37h
r2:	stax d
	inx d
        hlt
c1:	inr b
	sui 10h
        jnz r1
c2:	adi 30h
	jmp r2
```
Just before STAX D is called, DE register pair has 0090H. But on executing STAX D, the content of A isn't getting stored in 0090H.

**Comment by debjitbis08** [comment]
Thanks for reporting, I will look into it.
