### ISSUE TITLE
Add Comments by Ctrl + /

### ISSUE THREAD

**Issue by ydidwania** [debjitbis08/sim8085#8]
First of all, great work. Really helpful for 8085 beginners.
I think we should support commenting a block of lines by pressing `Ctrl + /` like other standard editors

**Comment by debjitbis08** [comment]
Thank you for the suggestion. This can be a nice little addition to the editor.

I will probably not work on this immediately, so feel free to implement this. Let me know if you are taking this up.

**Comment by techdharit1** [comment]
WHAT A CHANGE MUST DONE ON THE BUG I FOUND , PL. RESOLVE IT  .WHEN TO WORK I REQURED A PERFECT SOLUTION.

**Comment by nature-prakriti** [comment]
I am trying to implement this but unable to set up the environment

**Comment by debjitbis08** [comment]
Has been added in V2.
